apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-1
spec:
  selector:
    matchLabels:
      type: app  # label
  replicas: 2
  strategy:
    type: Recreate
  revisionHistoryLimit: 1  # 여러번 배포를 하더라도 하나의 replicaset만 남는다.
  template:
    metadata:
      labels:
        type: app  # label
    spec:
      containers:
      - name: container
        image: kubetm/app:v1
      terminationGracePeriodSeconds: 10
